spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/meet
    username: sa
    password:
    driver-class-name: org.h2.Driver
  messages:
    basename: messages,errors

  jpa:
    hibernate:
#      hibernate.hbm2ddl.auto: update
      ddl-auto: create
      use_sql_comments: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug
#    org.hibernate.type: trace
server:
  servlet:
    session:
      tracking-modes: cookie
